#!/usr/bin/env bash
# wach mazhar ola la

i=1

while [ "$i" -lt 11 ]; do

  # had mowafak
  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((i++))
done
