#!/usr/bin/env bash
# kalab kolchi mgd

file="school"

# kalab wach kayan
if [ -e "$file" ]; then

  echo "school file exists"

  # kaykalab alih
  if [ ! -s "$file" ]; then
    echo "school file is empty"

    # kaytof wach mgad
    if [ -f "$file" ]; then
      echo "school is a regular file"
    fi  

  else

    echo "school file is not empty"

    # kaykalab fih
    if [ -f "$file" ]; then
      echo "school is a regular file"
    fi  
  
  fi

else
  
  echo "school file does not exist"

fi
